### ISSUE TITLE
Doesn't seem to work with lastest version of Python 3.5.x

### ISSUE THREAD

**Issue by dizzy0ny** [discolabs/django-shopify-auth#25]
i've added the decorator to my index view:

```
from django.shortcuts import render
from shopify_auth.decorators import login_required

@login_required
def index(request, *args, **kwargs):
    products = []
    return render(request, "dst_app/home.html", {
        'products': products,
    })
```

But getting this error:
```
'QueryDict' object has no attribute 'iteritems'
on line 50 of:
C:\Dev\Python\Python35\lib\site-packages\shopify_auth\decorators.py in wrapper
            for k, v in request.GET.iteritems() 
```

**Comment by gavinballard** [comment]
Hmm. This looks like a regression from #18.

What version of Django are you using?

**Comment by dizzy0ny** [comment]
This is the version:

>>> import django
>>> django.VERSION
(1, 10, 3, 'final', 0)
```

**Comment by gavinballard** [comment]
Hmmm. @funkybob does this mean the changes in #18 should be reverted?

**Comment by funkybob** [comment]
Two options:
1. change it to request.GET.items()  ... I doubt iteritems is really gaining you anything.
2. change it to:

```
shopify_params = {
    k: request.GET[k]
    for k in {'shop', 'timestamp', 'signature', 'hmac'}
    if k in request.GET
}
```
so we only iterate the keys we care about, instead of all keys in request.GET.

**Comment by dizzy0ny** [comment]
How do i fix this if need be in the interim?  Any work-around other having to change your code locally?

**Comment by gavinballard** [comment]
@funkybob Thanks so much for chiming in. I've gone with the second solution for now. Hate that it isn't fully tested but not a lot of time my end these days.

@dizzy0ny I just pushed a new 0.4.8 release that should resolve this issue for you.

**Comment by dizzy0ny** [comment]
thanks @gavinballard !
